name: Birthday Checker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Print debug information'
        required: false
        default: 'false'

jobs:
  birthday_checker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML
        
    - name: Check birthdays
      id: check_birthdays
      run: |
        birthday_names=$(python birthday_checker.py)
        echo "::set-output name=birthday_names::$birthday_names"
        
    - name: Commit changes
      if: steps.check_birthdays.outputs.birthday_names != ''
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git commit -am "Automatic update: ${{ steps.check_birthdays.outputs.birthday_names }}"
        git push
