name: 更新生日列表

on:
  schedule:
    - cron: "0 17 * * *" # UTC时间17＝东八区1点
  workflow_dispatch: # 手动触发执行
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-birthday-list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: 安装依赖
        run: |
          pip install --upgrade pip
          python -m pip install pyyaml
          python -m pip install pytz
          python -m pip install lunardate

      - name: 运行脚本
        run: |
          python update.py
          python get-date.py

      - name: 检查是否有变更
        id: check_changes
        run: |
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            echo "CHANGES=true" >> $GITHUB_ENV
          fi

      - name: 提交变更
        if: env.CHANGES == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically update
