name: Update Birthday List

on:
  schedule:
    - cron: "0 0 * * *" # 每天午夜执行
  workflow_dispatch: # 手动触发执行
      
permissions:
  contents: write
  
jobs:

  get-last-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      # with:
      #   repository: W1ndys/Easy-QFNU
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
#    - name: Install dependencies
  #    run: python -m pip install requests
      
    - name: Get last commit
      run: python update.py

    - name: Check for changes
      id: check_changes
      run: |
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          echo "CHANGES=true" >> $GITHUB_ENV
        fi
          
    - name: Commit and push changes
      if: env.CHANGES == 'true'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatically update
